dist: trusty
sudo: false
language: node_js

env:
  global:
    - NG_CLI_ANALYTICS="ci" MOZ_HEADLESS=1

node_js: "12"

addons:
  firefox: latest

cache:
  directories:
    - ./node_modules
    - ~/.cache
    - ~/.npm

install:
  - npm ci

# Handle git submodules yourself
git:
  submodules: false
# Use sed to replace the SSH URL with the public URL, then initialize submodules
before_install:
  - export NG_CLI_ANALYTICS=ci
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules

script:
  - npm run install:financial
  - npm run build:financial
  - npm run build:lib
  - npm run test -- --watch=false --no-progress --browsers=FirefoxHeadless
  - ng serve &
  - $(npm bin)/wait-on http-get://localhost:4200/#
  - npm run test:main
  - kill $(jobs -p) || true
